3 and 4 channels default to rgb
scverse/spatialdata pull request #702
Opened 2024-09-08 09:36 UTC by LucaMarconato

The default parameter `rgb=False` in `to_spatial_image()` ([code here](https://github.com/spatial-image/spatial-image/blob/8bc3c54d6d8595f6ba217e97cf5e35f4716ab5bc/spatial_image.py#L1149)) implies that if we have an RGB image with no channels specified, the image will be parsed by calling its channels `'0', '1', ...`. This means that napari-spatialdata will show the image as separating channels and using grayscale coloring.

This PR sets `rgb=None`, which will set the default channel names to `'r', 'g', 'b'` (`'a'`) when `c_coords` is not set, leading to correct visualization in `napari-spatialdata`.

2024-09-08 09:36 UTC, LucaMarconato commented
Small PR, merging.

2024-09-08 10:33 UTC, LucaMarconato commented
the failing tests make it seems like that `r`, `g`, `b` is being set even when a 3-channel image had channel names already set.

2024-09-09 10:35 UTC, melonora approved these changes
Preapproving but please add a warning for the user. Typically with cyclic imaging you are dealing with 4 markers per imaging cycle which in that case should not be displayed as rgb. With this PR you think more of the people using visium. Either is fine for me but the behaviour should be clear.

2024-09-09 10:37 UTC, melonora requested changes
nvm tests will have to be fixed as well

2024-09-09 11:33 UTC, LucaMarconato commented
@melonora I think it should not be a problem because (after the tests are fixed), the RGB(A) will be used only if `c_coords` is not passed. In the case of 4-channel marker images the user is expected to pass the channel name.

2024-09-28 14:51 UTC, LucaMarconato commented
In the end since we are now passing `rgb=None` manually in `spatialdata-io`, I prefer (at least for now) to close this PR. I made a new PR instead that improves the docs: https://github.com/scverse/spatialdata/pull/716.

If user asks for automatically interpreting images as RGB(A) (for instance when adding external images), we can re introduce the approach of this PR and fix the tests.

2024-09-28 14:51 UTC, closed without merging